### ISSUE TITLE
p.SetConfig undefined (type *escpos.Escpos has no field or method SetConfig)

### ISSUE THREAD

**Issue by simaybocu** [hennedo/escpos#7]
![2022-09-20 (3)](https://user-images.githubusercontent.com/33957028/191218902-4ffbd5e8-7417-438e-a17c-61c3728ce5ca.png)

When I run it this way, it warns that there is no function here. Could you please check?

**Comment by sandisahdewo** [comment]
@simaybocu Why this issue was closed? Any idea how to solve it?
