### ISSUE TITLE
Printing from a printer with an internal IP

### ISSUE THREAD

**Issue by simaybocu** [hennedo/escpos#8]
I have a printer with internal IP of 192.168.0.10. And I am running the code below but it is not responding.

```go
package main

import (
	"net"
	"github.com/hennedo/escpos"
)
func main() {
	socket, err := net.Dial("ip4:1", "192.168.0.10")
	if err != nil {
		println(err.Error())
	}
	defer socket.Close()

	p := escpos.New(socket)
	p.Size(2, 2).Write("TEST")
}
```

 I guess it cannot connect. How do we find the part written "ip4:1", can you please help?

(edited by henne to wrap code into a code block)

**Comment by hennedo** [comment]
Hey!
You can see an example for the usage with net.Dial at the Readme.md of this project.
I guess you need to use ```net.Dial("tcp", "192.168.0.10:9100")```

**Comment by simaybocu** [comment]
> 

yes, I tried that way too, but still no output and no errors. I'm sure the printer connections are correct. Where else could I be doing wrong? Can you please help?

**Comment by hennedo** [comment]
What Printer are you using?
If net.Dial returns no error we can assume the connection is open, but it only means a connection is open, doesn't need to be the correct one.

Are you familiar with telnet? If you telnet to your printer using the same ip and port you should be able just to type some symbols and they (or at least something) should get printed. If this does not work the printer might not be compatible with the escpos protocol or its using a different port..

**Comment by simaybocu** [comment]
> What Printer are you using? If net.Dial returns no error we can assume the connection is open, but it only means a connection is open, doesn't need to be the correct one.
> 
> Are you familiar with telnet? If you telnet to your printer using the same ip and port you should be able just to type some symbols and they (or at least something) should get printed. If this does not work the printer might not be compatible with the escpos protocol or its using a different port..

Yes, by making the necessary adjustments with the telnet command
![2022-09-28](https://user-images.githubusercontent.com/33957028/192706947-6ec0e7e5-8f48-4b73-bdac-2eb1ea22aa70.png)
 and typing in the form of "test" over cmd, it gives output. But the code is still the same :(
I am using Epson A10 Thermal Receipt Printer.

**Comment by hennedo** [comment]
I just saw you did not call p.Print() or p.PrintAndCut() at the end of your code, which flushes the buffers, maybe this might be the solution

**Comment by simaybocu** [comment]
> I just saw you did not call p.Print() or p.PrintAndCut() at the end of your code, which flushes the buffers, maybe this might be the solution

yes, that worked!! Thank you so much for your support 🙏 😊
